version: '3'

services:
  web:
    build:
      context: . # where we want files and folders for this image to be pulled from
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # - /app/node_modules (original command in video, but changed to below cuz of error mentioned)
      - /home/node/app/node_modules
      # - .:/app (original command in video, but changed to below cuz of error mentioned)
      - .:/home/node/app

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    command: ["npm", "run", "test"]
